import type { Profile, TeamMember, DocumentRecord } from './types';

export const TEAM_MEMBERS: TeamMember[] = [
  { id: 'tm-1', name: 'Maj Josh Reissig', email: 'josh.reissig@us.af.mil', role: 'Admin' },
  { id: 'tm-2', name: 'Capt Sarah Chen', email: 'sarah.chen@us.af.mil', role: 'Provider' },
  { id: 'tm-3', name: 'TSgt Mike Rodriguez', email: 'mike.rodriguez@us.af.mil', role: 'Staff' },
  { id: 'tm-4', name: 'Capt Emily Vasquez', email: 'emily.vasquez@us.af.mil', role: 'Provider' },
];

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'p-1',
    name: 'Smith, John',
    rank: 'SSgt',
    afsc: '1A2X1 - Aircraft Loadmaster',
    unit: '62nd Airlift Wing',
    profileType: 'Code 37',
    startDate: '2025-11-18',
    expectedResolutionDate: '2026-03-15',
    primaryCondition: 'Chronic lumbar radiculopathy with L4-L5 disc herniation',
    assignedProvider: 'Maj Josh Reissig',
    status: 'Active',
    msdStatus: 'Does Not Meet',
    notes: [
      { id: 'n-1a', profileId: 'p-1', date: '2025-11-18', author: 'Maj Josh Reissig', type: 'note', content: 'Initial evaluation complete. MRI confirms L4-L5 disc herniation with nerve root impingement. Placed on Code 37 for flying duties.' },
      { id: 'n-1b', profileId: 'p-1', date: '2025-12-15', author: 'Capt Sarah Chen', type: 'note', content: 'Follow-up: Patient reports 40% improvement with physical therapy. Continue current treatment plan.' },
      { id: 'n-1c', profileId: 'p-1', date: '2026-01-20', author: 'Maj Josh Reissig', type: 'status_change', content: 'Approaching 90-day limit. Scheduled for orthopedic surgery consult.' },
      { id: 'n-1d', profileId: 'p-1', date: '2026-02-10', author: 'Capt Sarah Chen', type: 'note', content: 'Ortho consult recommends conservative management 4 more weeks before considering surgical intervention.' },
    ],
    documents: [],
    createdAt: '2025-11-18T08:00:00Z',
    updatedAt: '2026-02-10T14:30:00Z',
  },
  {
    id: 'p-2',
    name: 'Davis, Rachel',
    rank: 'A1C',
    afsc: '4N0X1 - Aerospace Medical Technician',
    unit: '375th Medical Group',
    profileType: 'Code 37',
    startDate: '2026-01-07',
    primaryCondition: 'Right knee ACL tear — post-surgical recovery',
    assignedProvider: 'Capt Emily Vasquez',
    status: 'Active',
    msdStatus: 'Pending Review',
    notes: [
      { id: 'n-2a', profileId: 'p-2', date: '2026-01-07', author: 'Capt Emily Vasquez', type: 'note', content: 'ACL reconstruction performed 01/05. Standard recovery protocol initiated. Profile for 6 months.' },
      { id: 'n-2b', profileId: 'p-2', date: '2026-02-01', author: 'Capt Emily Vasquez', type: 'note', content: 'Physical therapy progressing well. Range of motion improving. No complications.' },
      { id: 'n-2c', profileId: 'p-2', date: '2026-02-14', author: 'TSgt Mike Rodriguez', type: 'note', content: 'Updated duty limitations. Member cleared for light duty, no lifting >10lbs.' },
    ],
    documents: [],
    createdAt: '2026-01-07T09:00:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
  },
  {
    id: 'p-3',
    name: 'Thompson, Marcus',
    rank: 'TSgt',
    afsc: '2A3X3 - Tactical Aircraft Maintenance',
    unit: '1st Fighter Wing',
    profileType: 'IRILO',
    startDate: '2025-12-01',
    expectedResolutionDate: '2026-04-01',
    primaryCondition: 'Bilateral carpal tunnel syndrome',
    assignedProvider: 'Maj Josh Reissig',
    status: 'Active',
    msdStatus: 'Does Not Meet',
    notes: [
      { id: 'n-3a', profileId: 'p-3', date: '2025-12-01', author: 'Maj Josh Reissig', type: 'note', content: 'Nerve conduction study confirms moderate bilateral CTS. IRILO initiated — cannot perform maintenance duties requiring fine motor skills.' },
      { id: 'n-3b', profileId: 'p-3', date: '2026-01-15', author: 'Maj Josh Reissig', type: 'note', content: 'Right hand carpal tunnel release surgery scheduled for 02/01. Will re-evaluate after recovery.' },
      { id: 'n-3c', profileId: 'p-3', date: '2026-02-05', author: 'Capt Sarah Chen', type: 'note', content: 'Post-op day 4. Surgery successful. Recovery on track. Left hand surgery planned for March.' },
    ],
    documents: [],
    createdAt: '2025-12-01T08:00:00Z',
    updatedAt: '2026-02-05T11:00:00Z',
  },
  {
    id: 'p-4',
    name: 'Williams, Keisha',
    rank: 'SrA',
    afsc: '3D0X2 - Cyber Systems Operations',
    unit: '24th Air Force',
    profileType: 'IRILO',
    startDate: '2025-10-15',
    primaryCondition: 'Major depressive disorder with anxiety — stabilizing on medication',
    assignedProvider: 'Capt Sarah Chen',
    status: 'Pending Resolution',
    msdStatus: 'Pending Review',
    notes: [
      { id: 'n-4a', profileId: 'p-4', date: '2025-10-15', author: 'Capt Sarah Chen', type: 'note', content: 'Initial behavioral health referral. Started on sertraline 50mg. IRILO for duty limitations during stabilization period.' },
      { id: 'n-4b', profileId: 'p-4', date: '2025-11-20', author: 'Capt Sarah Chen', type: 'note', content: 'Medication adjusted to sertraline 100mg. Patient reporting improvement but still experiencing sleep disturbance.' },
      { id: 'n-4c', profileId: 'p-4', date: '2026-01-10', author: 'Capt Sarah Chen', type: 'status_change', content: 'Significant improvement noted. Considering profile resolution pending stable medication regimen for 90 days.' },
      { id: 'n-4d', profileId: 'p-4', date: '2026-02-15', author: 'Capt Sarah Chen', type: 'note', content: 'Stable on current regimen. Planning to resolve profile next month if no regression.' },
    ],
    documents: [],
    createdAt: '2025-10-15T08:00:00Z',
    updatedAt: '2026-02-15T09:00:00Z',
  },
  {
    id: 'p-5',
    name: 'Martinez, Carlos',
    rank: 'Capt',
    afsc: '11X - Pilot',
    unit: '55th Wing',
    profileType: 'ARILO',
    startDate: '2025-12-20',
    expectedResolutionDate: '2026-06-20',
    primaryCondition: 'Type 2 diabetes mellitus — newly diagnosed, controlled with metformin',
    assignedProvider: 'Maj Josh Reissig',
    status: 'Active',
    msdStatus: 'Does Not Meet',
    notes: [
      { id: 'n-5a', profileId: 'p-5', date: '2025-12-20', author: 'Maj Josh Reissig', type: 'note', content: 'A1C 7.2%. Started metformin 500mg BID. ARILO initiated — grounded from flying duties pending waiver review.' },
      { id: 'n-5b', profileId: 'p-5', date: '2026-01-20', author: 'Maj Josh Reissig', type: 'note', content: 'Follow-up: A1C improving. Dietary modifications showing effect. Continuing metformin.' },
      { id: 'n-5c', profileId: 'p-5', date: '2026-02-18', author: 'Maj Josh Reissig', type: 'note', content: 'ACS waiver package being prepared. A1C now 6.8%. Flight status pending waiver approval.' },
    ],
    documents: [],
    createdAt: '2025-12-20T08:00:00Z',
    updatedAt: '2026-02-18T10:00:00Z',
  },
  {
    id: 'p-6',
    name: 'Johnson, Tyler',
    rank: 'MSgt',
    afsc: '1T0X1 - Survival, Evasion, Resistance, Escape',
    unit: '336th Training Group',
    profileType: 'Standard Profile',
    startDate: '2026-01-25',
    primaryCondition: 'Right rotator cuff tear — partial thickness',
    assignedProvider: 'Capt Emily Vasquez',
    status: 'Active',
    msdStatus: 'Meets Standards',
    notes: [
      { id: 'n-6a', profileId: 'p-6', date: '2026-01-25', author: 'Capt Emily Vasquez', type: 'note', content: 'MRI confirms partial thickness rotator cuff tear. Conservative management with PT. Profile restricts overhead lifting and push-ups.' },
      { id: 'n-6b', profileId: 'p-6', date: '2026-02-15', author: 'Capt Emily Vasquez', type: 'note', content: 'PT progress satisfactory. Member motivated and compliant with restrictions.' },
    ],
    documents: [],
    createdAt: '2026-01-25T08:00:00Z',
    updatedAt: '2026-02-15T11:00:00Z',
  },
  {
    id: 'p-7',
    name: 'Park, Daniel',
    rank: 'Maj',
    afsc: '48XX - Aerospace Medicine Physician',
    unit: '711th Human Performance Wing',
    profileType: 'Standard Profile',
    startDate: '2026-02-01',
    primaryCondition: 'Post-concussion syndrome following TBI',
    assignedProvider: 'Capt Sarah Chen',
    status: 'Active',
    msdStatus: 'Pending Review',
    notes: [
      { id: 'n-7a', profileId: 'p-7', date: '2026-02-01', author: 'Capt Sarah Chen', type: 'note', content: 'Sustained TBI during PT session. Symptoms include persistent headaches, light sensitivity, and cognitive slowing. Profile initiated.' },
      { id: 'n-7b', profileId: 'p-7', date: '2026-02-14', author: 'Capt Sarah Chen', type: 'note', content: 'Neurology consult completed. Cognitive testing scheduled. Restricted from clinical duties.' },
    ],
    documents: [],
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-02-14T13:00:00Z',
  },
  {
    id: 'p-8',
    name: 'Anderson, Brittany',
    rank: 'SrA',
    afsc: '3E7X1 - Fire Protection',
    unit: '6th Civil Engineer Squadron',
    profileType: 'Standard Profile',
    startDate: '2025-12-10',
    primaryCondition: 'Stress fractures bilateral tibiae',
    assignedProvider: 'Capt Emily Vasquez',
    status: 'Active',
    msdStatus: 'Meets Standards',
    notes: [
      { id: 'n-8a', profileId: 'p-8', date: '2025-12-10', author: 'Capt Emily Vasquez', type: 'note', content: 'Bone scan confirms bilateral tibial stress fractures. Profile restricts running, marching, prolonged standing. Cross-training with swimming PT.' },
      { id: 'n-8b', profileId: 'p-8', date: '2026-01-10', author: 'Capt Emily Vasquez', type: 'note', content: '4-week follow-up: Pain improving. Bone healing on track. Continue restrictions.' },
      { id: 'n-8c', profileId: 'p-8', date: '2026-02-10', author: 'TSgt Mike Rodriguez', type: 'note', content: '8-week follow-up: Significant improvement. Planning gradual return to full duty over next 4 weeks.' },
    ],
    documents: [],
    createdAt: '2025-12-10T08:00:00Z',
    updatedAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'p-9',
    name: 'Lee, James',
    rank: 'Lt Col',
    afsc: '12X - Combat Systems Officer',
    unit: '552nd Air Control Wing',
    profileType: 'MEB Referral',
    startDate: '2025-09-01',
    primaryCondition: 'Chronic migraine disorder with aura — failed multiple medication trials',
    assignedProvider: 'Maj Josh Reissig',
    status: 'Referred to MEB',
    msdStatus: 'Does Not Meet',
    notes: [
      { id: 'n-9a', profileId: 'p-9', date: '2025-09-01', author: 'Maj Josh Reissig', type: 'note', content: 'Chronic migraines with visual aura, 8-10 episodes/month. Failed topiramate, amitriptyline, and propranolol. Botox injections partially effective.' },
      { id: 'n-9b', profileId: 'p-9', date: '2025-10-15', author: 'Maj Josh Reissig', type: 'status_change', content: 'Does not meet retention standards for rated duties. Initiating MEB referral.' },
      { id: 'n-9c', profileId: 'p-9', date: '2025-11-20', author: 'TSgt Mike Rodriguez', type: 'document', content: 'NARSUM completed and submitted to MEB. Package includes all neurology consults and medication trials.' },
      { id: 'n-9d', profileId: 'p-9', date: '2026-02-01', author: 'Maj Josh Reissig', type: 'note', content: 'MEB findings pending. Member has been briefed on IDES process. PEBLO assigned.' },
    ],
    documents: [],
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'p-10',
    name: 'Garcia, Maria',
    rank: 'TSgt',
    afsc: '1C0X2 - Aviation Resource Management',
    unit: '89th Airlift Wing',
    profileType: 'Standard Profile',
    startDate: '2025-08-15',
    primaryCondition: 'Pregnancy-related temporary duty limitations',
    assignedProvider: 'Capt Sarah Chen',
    status: 'Resolved',
    msdStatus: 'Meets Standards',
    notes: [
      { id: 'n-10a', profileId: 'p-10', date: '2025-08-15', author: 'Capt Sarah Chen', type: 'note', content: 'Standard pregnancy profile initiated. Duty limitations per AFI 44-102.' },
      { id: 'n-10b', profileId: 'p-10', date: '2025-12-01', author: 'Capt Sarah Chen', type: 'note', content: 'Normal delivery. Postpartum recovery on track.' },
      { id: 'n-10c', profileId: 'p-10', date: '2026-02-01', author: 'Capt Sarah Chen', type: 'status_change', content: 'Postpartum clearance complete. Full duty status restored. Profile resolved.' },
    ],
    documents: [],
    createdAt: '2025-08-15T08:00:00Z',
    updatedAt: '2026-02-01T08:00:00Z',
  },
];

export const MOCK_DOCUMENTS: DocumentRecord[] = [
  { id: 'd-1', type: 'narsum', title: 'NARSUM — Lt Col Lee', subject: 'Chronic migraine with aura', profileId: 'p-9', content: '', createdAt: '2025-11-20T10:00:00Z', createdBy: 'Maj Josh Reissig' },
  { id: 'd-2', type: 'memo', title: 'Duty Limitation Memo — SSgt Smith', subject: 'Temporary duty restrictions', profileId: 'p-1', content: '', createdAt: '2025-12-01T09:00:00Z', createdBy: 'Maj Josh Reissig' },
  { id: 'd-3', type: 'dd2992', title: 'DD 2992 — Capt Martinez', subject: 'Flight status — DNIF', profileId: 'p-5', content: '', createdAt: '2025-12-22T14:00:00Z', createdBy: 'Maj Josh Reissig' },
  { id: 'd-4', type: 'limdu', title: 'LIMDU — A1C Davis', subject: 'Post-surgical ACL recovery', profileId: 'p-2', content: '', createdAt: '2026-01-08T11:00:00Z', createdBy: 'Capt Emily Vasquez' },
  { id: 'd-5', type: 'discharge', title: 'Discharge Summary — SrA Anderson', subject: 'Stress fracture management', profileId: 'p-8', content: '', createdAt: '2026-02-10T16:00:00Z', createdBy: 'Capt Emily Vasquez' },
  { id: 'd-6', type: 'script', title: 'Rx — SrA Williams', subject: 'Sertraline 100mg', profileId: 'p-4', content: '', createdAt: '2026-02-15T08:00:00Z', createdBy: 'Capt Sarah Chen' },
];
